brendanhay/gogol

- gogol/src/Network/Google/Auth.hs
- gogol/src/Network/Google/Internal/Auth.hs
BigQuery connections were failing with `Invalid Credentials`, and the failing request had an authorization header that was missing the `Bearer ` prefix.
This fixes the problem in BigQuery, but the real problem is probably that instances of `ToHttpApiData` for other types of tokens are not adding the `Bearer ` prefix.
> Hack to fix a bug that caused BigQuery connections to fail.

- core/src/Network/Google/Types.hs
`CaptureMode "projectId" "commit"` currently (incorrectly) is serialised to a path parameter of `"projectIdcommit"` instead of the desired `"projectId:commit"`.
Fixes #33
> Adding missing colon separator when CaptureModes are serialised

- gogol/src/Network/Google/Auth/InstalledApplication.hs
- gogol/src/Network/Google/Internal/Auth.hs
Currently, the InstalledApplication module retrieves the authorization code from the user but when it tries to exchange that code for an oauth token it queries the wrong endpoint (accounts.google.com). It needs to query the endpoint to exchange tokens, not the original accounts endpoint. This is documented at https://developers.google.com/identity/protocols/OAuth2InstalledApp#handlingtheresponse.
> Create a token request to exhange authorization code with token.

- README.md
These references in the README let me stumble on reading. Likely where inherited from the sibling project that deals with AWS.
> Fix README to reference the GCE instead of AWS

- gogol/src/Network/Google/Auth.hs
- gogol/src/Network/Google/Auth/ApplicationDefault.hs
- gogol/src/Network/Google/Auth/InstalledApplication.hs
- gogol/src/Network/Google/Internal/Auth.hs
I added the several functions to save/refresh FromClient-constructed `Credentials`. 
After initial authorization, an `accessToken` can be refresh by `refreshStore`. As well as, it can be converted to `AuthorizedUser` and saved. Next time, users can read it directly.
Moreover, I added an `assess_type` param to form URL.
> added offline mode and save/refresh FromClient-constructed Credentials functions

- core/src/Network/Google/Data/Time.hs
Google in [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest) documentation explain that duration have to end with s.
A duration in seconds with up to nine fractional digits, terminated by 's'. Example: "3.5s".
[Here](https://gist.github.com/d61h6k4/5274d64c44c766218ca706104a87ae2d) example what is the behaviour is now. Pull request is fix that.
> Change Duration FromHttpApiData instance. Append s symbol to the end.

- gogol/src/Network/Google.hs
Looks like the package `tiny-log` should be `tinylog`.
> tiny-log -> tinylog

- core/src/Network/Google/Prelude.hs
- core/src/Network/Google/Types.hs
`servant-0.13` introduces it's own `Stream` type. I'm not sure if you prefer CPP for the `hiding` (so there are no warnings for versions earlier than 0.13) - if so, let me know, and I'm happy to change it.
> Fix import conflicts for servant 0.13.

- gen/stack.yaml
This allows me to build without adding these to my user environment under NixOS. I am not very familiar with Stack+Nix so I followed this documentation:
https://docs.haskellstack.org/en/stable/nix_integration/
If the `shell.nix` route is preferable I can generate that instead, feedback is welcome!
> nix: add nixpkgs for building gen

- core/src/Network/Google/Types.hs
This is backwards-compatible and although there is no full ghc-8.4.3
and lts-12.9 support yet, this is useful for projects that mix in
gogol.
> Fix build of core with base-4.11.0

- gen/annex/bigquery.json
- gogol-bigquery/gen/Network/Google/BigQuery/Types/Product.hs
In the latest version, there is a stray default for the `requirePartitionFilter`, even though there is a default value ( `False` ) creation of a table fails if the target is not a partitioned table.
I also think this is a common issue, and we won't be able to pinpoint each similar error until we come across during use. This probably requires a more generic solution like setting a field to `Maybe` if the field's description contains the keyword `[Optional]`.
> [gogol-bigquery] parameter 'requirePartitionFilter' needs to be Optional

- gen/gogol-gen.cabal
- gen/src/Gen/AST/Flatten.hs
- gen/src/Gen/AST/Render.hs
- gen/src/Gen/AST/Solve.hs
- gen/src/Gen/Formatting.hs
- gen/src/Gen/IO.hs
- gen/src/Gen/Orphans.hs
- gen/src/Gen/Syntax.hs
- gen/src/Gen/Text.hs
- gen/src/Gen/Tree.hs
- gen/src/Gen/Types/Data.hs
- gen/src/Gen/Types/Help.hs
- gen/src/Gen/Types/Id.hs
- gen/src/Gen/Types/NS.hs
- gen/src/Gen/Types/Schema.hs
- gen/stack.yaml
- stack-8.6.3.yaml
*This is my first meddling with `haskell-src-exts`, so please take caution while reviewing this PR.*
What I did was mostly adding missing `()` which was introduced in data types from `haskell-src-exts` as  the annotation parameter `l`, which it seems is not necessary in our case.
This probably shouldn't be merged until `hindent` package has a new release since the latest version has a bug that causes a termination of the gogol-gen. That bug is fixed in the upstream, hence the additional `extra-deps` inside `gen/stack.yaml`.
I don't think the requirements above should prevent me from sending this PR, since they're all about upstream issues that are fixed but not yet released.
---
Regarding this upgrade, I took `gogol-drive` as my basis of comparison, so the resulting files are nearly …
> Upgraded gogol-gen to work with lts-13 (ghc-8.6.3)

- gogol/src/Network/Google/Auth/InstalledApplication.hs
We're requesting to the wrong endpoint (https://accounts.google.com/o/oauth2/v2/auth) at the moment.
The correct one (https://www.googleapis.com/oauth2/v4/token) is inside `tokenRequest`.
Related PR for `ServiceAccount`: https://github.com/brendanhay/gogol/pull/55.
Related documentation: https://developers.google.com/identity/protocols/OAuth2InstalledApp#offline
> fix InstalledApplication's refreshToken

- core/gogol-core.cabal
- core/src/Network/Google/Prelude.hs
`Servant.Utils.Links` was deprecated in `servant` 14.1 - https://github.com/haskell-servant/servant/pull/998
It has now been removed entirely in `servant` 0.17, which breaks `gogol-core` from building. Switching to the non-deprecated module path fixes it.
This does mean that `gogol-core` will not build on older than `servant` 14.1. However 14.1 was released 6 Jul 2018, so I'm hoping that is ok?
Hmm..
ghc 8.6.4 - `lts-13.19` uses `servant` 0.15 :heavy_check_mark: 
ghc 8.4.4 - `lts-12.26` uses `servant` 0.14.1 :heavy_check_mark: 
ghc 8.2.2 - `lts-11.22` uses `servant` 0.13 :no_good_man: 
So I guess as is this would require dropping ghc 8.2.2 support..
> Avoid deprecated servant import. It was removed in 0.17

- gogol/src/Network/Google/Auth/ServiceAccount.hs
The `ServiceAccount` is required to create an `OAuthToken`, but it wasn't exported from anywhere, so there wasn't an easy way of creating it.
I exported it from `Network.Google.Auth.ServiceAccount`.
> Explicitly export ServiceAccount

- gen/annex/youtube.json
- gen/src/Gen/AST/Solve.hs
- gen/src/Gen/Types.hs
- gen/src/Gen/Types/Schema.hs
Hi,
I've fixed a couple of issues in the 2 commits so far. I'm mostly cargo culting the fixes so it could be the wrong solution, but it seems to make it pass.
The next issue I don't know how to fix:
```
[206/215] model:videointelligence
-> Reading /home/bananan/dead/gogol/gen/annex/videointelligence.json
-> Reading /home/bananan/dead/gogol/gen/model/videointelligence/v1p3beta1/videointelligence-api.json
-> Successfully parsed 'videointelligence' API definition.
gogol-gen: Error prefixing: GoogleCloudVideointelligenceV1p1beta1_DetectedLandmark
Fields: ["confidence","point","name"]
Matches: 
gcvvdl => Just (fromList ["confidence","point","name"])
g => Just (fromList ["feature","alternatives","languageCode","bottom","annotationProgress","rotatedBoundingBox","startTime","categoryEntities","tim …
```
> Fix generation

- gen/gogol-gen.cabal
- gen/src/Gen/AST/Flatten.hs
- gen/src/Gen/AST/Render.hs
- gen/src/Gen/AST/Solve.hs
- gen/src/Gen/IO.hs
- gen/src/Gen/Syntax.hs
- gen/src/Gen/Types.hs
- gen/src/Gen/Types/Help.hs
- gen/src/Gen/Types/Schema.hs
- gen/src/Main.hs
- gen/stack.yaml
- gen/stack.yaml.lock
Hello there! Let's try this again, but this time well-tested, and updated to the last lts.
This makes it easier to build it with a recent nixpkgs.
I also updated the non-stackage dependencies.
The new doclayout dependency was an extracted piece of pandoc we depend on. The rest of the changes are warning squashing.
> Gen: Upgrade to lts-17.12 

- gen/src/Gen/Text.hs
Hi there!
I noticed that, while the regeneration now works, the result doesn't build for all packages.
Here is a fix!
----- 
The `Secure` and `DateTime` are now appearing in the api, but they are (as well
as `DateTime'`) already used in `Network.Gogol.Prelude`. Adding them to the list
of reserved names fixes the build.
On top of that, this commits ensures that the named picked by `renamedReserved`
is not itself reverved (so that `DateTime` is changed to `DateTime''`).
> Add more reserved names to fix build with new models

- gen/src/Gen/AST/Solve.hs
So, I found this bug when trying to build everything with a newer model. It was a fun ride to debug, and I hope the following explanation give a good idea of what's happening here.
This change, along with #159 and #162, are all I needed to be able update the model, regenerate every package, and make sure everything compiles! The only thing left I want to do is see how much I can update the stackage version (and the bounds) for the `gogol` packages. And then I can offer a huge regeneration PR!
----
`getPrefix` is function responsible for giving prefix to record members so that every
single identifier is unique. It does that by looking through a list of candidate prefixes,
and for each, checking that no other record with the same prefix has any field in common.
However, it does that before …
> Fix identifier conflict because of mixed case in the api definition

- gogol/gogol.cabal
- gogol/src/Network/Google/Auth.hs
- gogol/src/Network/Google/Auth/TokenFile.hs
- gogol/src/Network/Google/Internal/Auth.hs
- gogol/src/Network/Google/Internal/Logger.hs
- stack-8.10.7.yaml
- stack.yaml
- stack.yaml.lock
A quick hack to support GKE workload identity and parity with [kubernetes-client's](https://hackage.haskell.org/package/kubernetes-client-0.3.2.0/docs/src/Kubernetes.Client.Auth.TokenFile.html) default method of in-cluster credentials discovery.
> Add support for GKE (kubernetes) service accounts

- flake.nix
This allows ex: `nix build .#gogol-gmail`
note that this causes:
```
❯ nix flake show 
git+file:///home/imalison/Projects/gogol?ref=refs/heads/addRealFlake&rev=09c59df08df2f9de321532dc011b58ce8785dd62
├───defaultPackage
│   ├───aarch64-darwin omitted (use '--all-systems' to show)
│   ├───aarch64-linux omitted (use '--all-systems' to show)
│   ├───i686-linux omitted (use '--all-systems' to show)
│   ├───x86_64-darwin omitted (use '--all-systems' to show)
error:
… while evaluating the attribute 'defaultPackage'
at /nix/store/gf87d4imyf2wdmwbbbpnlz65za5xmvnj-source/flake.nix:51:5:
50|     packages = builtins.listToAttrs (map mkPackage allPackages);
51|     defaultPackage = self.packages.${system}.gogol;
|     ^
52|   }) // { inherit hoverlay overlay overlays; } ;
… while evaluating the …
```
> Support all services packages in flake
